### ISSUE TITLE
Matrix p = ?, when training on cifar-100 using Forward and Backward

### ISSUE THREAD

**Issue by zhangchbin** [YisenWang/symmetric_cross_entropy_for_noisy_labels#1]

**Comment by YisenWang** [comment]
The same as SL. Please run SL first then P will be saved.

**Comment by zhangchbin** [comment]
> The same as SL. Please run SL first then P will be saved.

if noise_rate = 0., then the P will be Identity matrix?
And Forward will be equal to normal cross entropy?

**Comment by YisenWang** [comment]
Yes
