### ISSUE TITLE
Why Results reported in SL and D2L are different?

### ISSUE THREAD

**Issue by XinshaoAmosWang** [YisenWang/symmetric_cross_entropy_for_noisy_labels#3]
Hi @YisenWang @xingjunm 
I happened to find that you are authors of both SL and D2L. 
It is common that results are different if they are from different authors because of implementation and training details. 
However, **since you are authors of both SL and D2L, I am wondering why the reported results on CIFAR-100 with the same network ResNet44 are quite different.** 

**CIFAR-100 (Results From D2L ICML 2018)**
Noise Rate cross-entropy forward backward boot-hard boot-soft **D2L**
0% **68.20±0.2** 68.54±0.3 68.48±0.3 68.31±0.2 67.89±0.2 **68.60±0.3**
20% **52.88±0.2** 60.25±0.2 58.74±0.3 58.49±0.4 57.32±0.3 **62.20±0.4**
40% **42.85±0.2** 51.27±0.3 45.42±0.2 44.41±0.1 41.87±0.1 **52.01±0.3**
60% **30.09±0.2** 41.22±0.3 34.49±0.2 36.65±0.3 32.29±0.1 **42.27±0.2**

**CIFAR-100 (Results From SL ICCV 2019)**
Noise rate 0.0     0.2                    0.4                       0.6 
**CE 64.34 ± 0.37 59.26 ± 0.39 50.82 ± 0.19 25.39 ± 0.09** 
LSR 63.68 ± 0.54 58.83 ± 0.40 50.05 ± 0.31 24.68 ± 0.43 
Bootstrap 63.26 ± 0.39 57.91 ± 0.42 48.17 ± 0.18 12.27 ± 0.11 
Forward 63.99 ± 0.52 59.75 ± 0.34 53.13 ± 0.28 24.70 ± 0.26 
**D2L 64.60 ± 0.31 59.20 ± 0.43 52.01 ± 0.37 35.27 ± 0.28** 
GCE 64.43 ± 0.20 59.06 ± 0.27 53.25 ± 0.65 36.16 ± 0.74 
SL 66.75 ± 0.04 60.01 ± 0.19 53.69 ± 0.07 41.47 ± 0.04 

Results From SL ICCV 2019 are generally lower than  Results From D2L IMCL 2018. 

I would like to compare with your reported results. I am wondering which one to compare against? 
Thanks.

**Comment by YisenWang** [comment]
Hi, if you check the code of SL and D2L, you will find there are some difference on implementation, e.g., optimizer. For the comparison, I suggest you to re-run the code using your own setting.

**Comment by XinshaoAmosWang** [comment]
Thanks. 

Then, in your SL, Does Bootstrap denote Bootstrap-soft?

**Comment by YisenWang** [comment]
Bootstrap-hard
