### ISSUE TITLE
Is symmetric_cross_entropy suitable for binary classification issue?

### ISSUE THREAD

**Issue by useric** [YisenWang/symmetric_cross_entropy_for_noisy_labels#4]
Is `symmetric_cross_entropy` suitable for binary classification issue?
If so, someone can give some hints to modify the  `symmetric_cross_entropy` function?

**Comment by YisenWang** [comment]
symmetric_cross_entropy is definitely suitable for binary case where the one-hot label is [0,1] or [1,0].
