### ISSUE TITLE
About alpha and beta

### ISSUE THREAD

**Issue by Zhengtq** [YisenWang/symmetric_cross_entropy_for_noisy_labels#7]
Why the settings of alpha\beta in the task of cifar10 and cifar100 are **vastly** differently?
For cifar10, the setting is α = 0.1  β = 1.0.
For cifar100, the setting is α = 6.0 β = 0.1.

**Comment by YisenWang** [comment]
Please refer to this issue comment https://github.com/YisenWang/symmetric_cross_entropy_for_noisy_labels/issues/5#issuecomment-624482093
